version: "3.8"


services:
  api:
    build:
      context: .
      dockerfile: dockerfile.local
    image: golang-chat-api:latest
    container_name: golang-chat-api
    ports:
      - "${API_PORT:-8080}:8080"
    depends_on:
      - mongo
    environment:
      MONGO_URI: "mongodb://mongo:27017/chat"
    volumes:
      - .:/home/docker/workspace

  mongo:
    image: mongo:6.0
    container_name: golang-chat-mongo
    ports:
      - "${MONGO_PORT:-27017}:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: chat

  mongo-express:
    image: mongo-express:1.0.0-alpha.4
    container_name: golang-chat-mongo-express
    ports:
      - "${MONGO_EXPRESS_PORT:-8081}:8081"
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: ""
      ME_CONFIG_MONGODB_ADMINPASSWORD: ""
      ME_CONFIG_OPTIONS_EDITORTHEME: "ambiance"

volumes:
  mongo_data:
